#####################################################################################################
# This file only contains the default configuration!                                                #
# Environment-specific settings should be placed in a application-[dev|prod|test].yml file          #
# or by using OS environment variables. For more information on how to configure Spring see         #
# https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html #
#####################################################################################################

spring:
  profiles:
    # The application runs in dev mode by default! Override this in production mode!
    active: dev
  batch:
    job:
      enabled: false
    initialize-schema: always
  data.ldap.repositories.enabled: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  liquibase:
    change-log: classpath:db/changelog-master.yaml
    parameters:
      collectionStoragePath: ${codefreak.files.fileSystem.collectionStoragePath}

logging:
  level:
    # Hides HHH000424: Disabling contextual LOB creation as createClob() method threw error
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: WARN
    # Hide log spam of docker pull progress
    com.spotify.docker.client.LoggingPullHandler: WARN
    notprivacysafe.graphql.execution.SimpleDataFetcherExceptionHandler: ERROR

graphql:
  packages:
    - "org.codefreak.codefreak.graphql.api"

server:
  error:
    # there is a custom ErrorController that will include the stacktrace in dev environment
    include-stacktrace: never
  servlet:
    session:
      # Set server-side timeout of cookies
      # The client session-cookie will expire on browser close by default
      timeout: 24h
      # Do not persist sessions between server restarts
      # This will lead to weird issues where Tomcat's and Spring's session storage get out of sync
      persistent: false

codefreak:
  instanceId: default
  files:
    adapter: file_system
    fileSystem:
      # The path where all file collections will be stored in sub-directories
      # Please make sure that the user running the server has read+write permissions on this directory
      collectionStoragePath: "${user.home}/.codefreak/${codefreak.instanceId}"
  docker:
    # All of the docker settings below will fall back to a system-depended default value if unset
    host: ~
    certPath: ~
    caCertPath: ~
    clientKeyPath: ~
    clientCertPath: ~
    # Define how (and if) images will be pulled on application startup
    pull-policy: always
  ide:
    image: "cfreak/ide:1"
    # Interval for checking for idle containers in ms. Default 30 seconds.
    idle-check-rate: 30000
    # Time span after which an idle container is shut down. Default 1 minute.
    idle-shutdown-threshold: 60000
    # Memory limit in bytes (2GiB)
    memory: 2147483648
    # Number of CPUs per container (0 means no limit)
    cpus: 0
    # Name of the network the container will be attached to
    network: bridge

# Enable actuator health checks if needed in production
# https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#actuator-properties
management:
  health:
    defaults:
      enabled: false
