# This is a default application.yml for Code FREAK that is templated by Helm
# A user may override settings using .Values.applicationYmlOverrides
codefreak:
  docker:
    # Remove this when all Docker deps have been removed
    optional: true
  ide:
    idle-check-rate: 2147483647
  workspaces:
    idleCheckInterval: 30000
    baseUrlTemplate: http://minikube/{workspaceIdentifier}
    namespace: {{ .Release.Namespace }}
logging:
  level:
    org.codefreak.codefreak: DEBUG

{{ if eq .Values.config.database.type "postgres" }}
{{ with .Values.config.database.postgres }}
spring:
  datasource:
    url: jdbc:postgresql://{{ .host }}:{{ .port }}/{{ .database }}
    username: {{ .username | toYaml }}
    {{ if .password }}
    password: {{ .password | toYaml }}
    {{ end }}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        globally_quoted_identifiers: true
{{ end }}
{{ end }}
